spring:
  mongodb:
    embedded:
      version: 3.5.5
  data:
    mongodb:
      database: library
      port: 0
  datasource:
    url: jdbc:h2:mem:library
  sql:
    init:
      mode: always
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.spring.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

logging:
  level:
    root: info
    org.springframework: info