INSERT INTO authors (`name`)
VALUES      ('Stephen King')
        ,   ('Viktor Pelevin')
        ,   ('Strugatsky Brothers');

INSERT INTO genres (`name`)
VALUES      ('Horror')
        ,   ('Thriller')
        ,   ('Dark fantasy')
        ,   ('Coming-of-age story')
        ,   ('Science fiction')
        ,   ('Western')
        ,   ('Absurdist fiction')
        ,   ('Satire')
        ,   ('Novel');

INSERT INTO books (`author_id`,`name`)
VALUES      (1, '''Salem''s Lot')
        ,   (1, 'It')
        ,   (1, 'The Dark Tower')
        ,   (2, 'Omon Ra')
        ,   (2, 'Chapayev and Void')
        ,   (2, 'Generation "P"')
        ,   (3, 'Hard to Be a God')
        ,   (3, 'Monday Begins on Saturday')
        ,   (3, 'Roadside Picnic');

INSERT INTO books_genres (`book_id`,`genre_id`)
VALUES      ((SELECT id FROM books WHERE name = '''Salem''s Lot')            , (SELECT id FROM genres WHERE name='Horror'))
        ,   ((SELECT id FROM books WHERE name = 'It')                        , (SELECT id FROM genres WHERE name='Horror'))
        ,   ((SELECT id FROM books WHERE name = 'It')                        , (SELECT id FROM genres WHERE name='Thriller'))
        ,   ((SELECT id FROM books WHERE name = 'It')                        , (SELECT id FROM genres WHERE name='Dark fantasy'))
        ,   ((SELECT id FROM books WHERE name = 'It')                        , (SELECT id FROM genres WHERE name='Coming-of-age story'))
        ,   ((SELECT id FROM books WHERE name = 'The Dark Tower')            , (SELECT id FROM genres WHERE name='Dark fantasy'))
        ,   ((SELECT id FROM books WHERE name = 'The Dark Tower')            , (SELECT id FROM genres WHERE name='Science fiction'))
        ,   ((SELECT id FROM books WHERE name = 'The Dark Tower')            , (SELECT id FROM genres WHERE name='Horror'))
        ,   ((SELECT id FROM books WHERE name = 'The Dark Tower')            , (SELECT id FROM genres WHERE name='Western'))
        ,   ((SELECT id FROM books WHERE name = 'Omon Ra')                   , (SELECT id FROM genres WHERE name='Science fiction'))
        ,   ((SELECT id FROM books WHERE name = 'Omon Ra')                   , (SELECT id FROM genres WHERE name='Absurdist fiction'))
        ,   ((SELECT id FROM books WHERE name = 'Omon Ra')                   , (SELECT id FROM genres WHERE name='Satire'))
        ,   ((SELECT id FROM books WHERE name = 'Chapayev and Void')         , (SELECT id FROM genres WHERE name='Novel'))
        ,   ((SELECT id FROM books WHERE name = 'Generation "P"')            , (SELECT id FROM genres WHERE name='Novel'))
        ,   ((SELECT id FROM books WHERE name = 'Hard to Be a God')          , (SELECT id FROM genres WHERE name='Science fiction'))
        ,   ((SELECT id FROM books WHERE name = 'Monday Begins on Saturday') , (SELECT id FROM genres WHERE name='Science fiction'))
        ,   ((SELECT id FROM books WHERE name = 'Roadside Picnic')           , (SELECT id FROM genres WHERE name='Science fiction'));
