spring:
  mongodb:
    embedded:
      version: 3.5.5
  data:
    mongodb:
      database: library
      port: 0
    rest:
      basePath: /datarest
  datasource:
    url: jdbc:h2:mem:library;MODE=LEGACY;
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.spring.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

logging:
  level:
    root: info
    org.springframework: info
  file:
    path: log

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
