spring:

  data:
    mongodb:
      database: library
      host: localhost
      port: 27017
    rest:
      basePath: /datarest
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: postgres
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.spring.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local

logging:
  level:
    root: info
    org.springframework: info
  file:
    path: log

management:
  endpoints:
    web:
      exposure:
        include:
          - "logfile"
          - "health"
          - "metrics"
          - "prometheus"
  endpoint:
    health:
      show-details: always
