INSERT INTO authors (`name`)
VALUES      ('Stephen King')
        ,   ('Viktor Pelevin')
        ,   ('Strugatsky Brothers');

INSERT INTO genres (`name`)
VALUES      ('Horror')
        ,   ('Thriller')
        ,   ('Dark fantasy')
        ,   ('Coming-of-age story')
        ,   ('Science fiction')
        ,   ('Western')
        ,   ('Absurdist fiction')
        ,   ('Satire')
        ,   ('Novel');

INSERT INTO books (`author_id`,`name`)
VALUES      (1, '''Salem''s Lot')
        ,   (1, 'It')
        ,   (1, 'The Dark Tower')
        ,   (2, 'Omon Ra')
        ,   (2, 'Chapayev and Void')
        ,   (2, 'Generation "P"')
        ,   (3, 'Hard to Be a God')
        ,   (3, 'Monday Begins on Saturday')
        ,   (3, 'Roadside Picnic');

INSERT INTO books_genres (`book_id`,`genre_id`)
VALUES      ((SELECT id FROM books WHERE name = '''Salem''s Lot')            , (SELECT id FROM genres WHERE name='Horror'))
        ,   ((SELECT id FROM books WHERE name = 'It')                        , (SELECT id FROM genres WHERE name='Horror'))
        ,   ((SELECT id FROM books WHERE name = 'It')                        , (SELECT id FROM genres WHERE name='Thriller'))
        ,   ((SELECT id FROM books WHERE name = 'It')                        , (SELECT id FROM genres WHERE name='Dark fantasy'))
        ,   ((SELECT id FROM books WHERE name = 'It')                        , (SELECT id FROM genres WHERE name='Coming-of-age story'))
        ,   ((SELECT id FROM books WHERE name = 'The Dark Tower')            , (SELECT id FROM genres WHERE name='Dark fantasy'))
        ,   ((SELECT id FROM books WHERE name = 'The Dark Tower')            , (SELECT id FROM genres WHERE name='Science fiction'))
        ,   ((SELECT id FROM books WHERE name = 'The Dark Tower')            , (SELECT id FROM genres WHERE name='Horror'))
        ,   ((SELECT id FROM books WHERE name = 'The Dark Tower')            , (SELECT id FROM genres WHERE name='Western'))
        ,   ((SELECT id FROM books WHERE name = 'Omon Ra')                   , (SELECT id FROM genres WHERE name='Science fiction'))
        ,   ((SELECT id FROM books WHERE name = 'Omon Ra')                   , (SELECT id FROM genres WHERE name='Absurdist fiction'))
        ,   ((SELECT id FROM books WHERE name = 'Omon Ra')                   , (SELECT id FROM genres WHERE name='Satire'))
        ,   ((SELECT id FROM books WHERE name = 'Chapayev and Void')         , (SELECT id FROM genres WHERE name='Novel'))
        ,   ((SELECT id FROM books WHERE name = 'Generation "P"')            , (SELECT id FROM genres WHERE name='Novel'))
        ,   ((SELECT id FROM books WHERE name = 'Hard to Be a God')          , (SELECT id FROM genres WHERE name='Science fiction'))
        ,   ((SELECT id FROM books WHERE name = 'Monday Begins on Saturday') , (SELECT id FROM genres WHERE name='Science fiction'))
        ,   ((SELECT id FROM books WHERE name = 'Roadside Picnic')           , (SELECT id FROM genres WHERE name='Science fiction'));

INSERT INTO comments (`book_id`,`text`)
VALUES      (1, 'All or nothing')
        ,   (1, 'A little bird told me…')
        ,   (1, 'Don’t judge a book by it’s cover')
        ,   (2, 'To live a cat and dog life')
        ,   (2, 'Kill two birds with one stone')
        ,   (2, 'Your roof is running away from you')
        ,   (3, 'You rock!')
        ,   (3, 'Nobody’s perfect, but me')
        ,   (3, 'Things don’t always work out the first time')
        ,   (4, 'Being between hammer and anvil')
        ,   (4, 'After a storm comes a calm')
        ,   (4, 'The sun will shine on our side of the fence')
        ,   (5, 'The right man in the right place')
        ,   (5, 'Better late than never')
        ,   (5, 'If there is a will, there is a way')
        ,   (6, 'A good heart’s worth gold')
        ,   (6, 'Happiness is not a destination. It is a method of life')
        ,   (6, 'An hour in the morning is worth two in the evening')
        ,   (7, 'It takes two to tango')
        ,   (7, 'It takes two to lie. One to lie and one to listen')
        ,   (7, 'Success does not consist in never making mistakes but in never making the same one a second time')
        ,   (8, 'Simplicity is the ultimate sophistication')
        ,   (8, 'Always forgive your enemies; nothing annoys them so much')
        ,   (8, 'Your time is limited, so don’t waste it living someone else’s life')
        ,   (9, 'No two persons ever read the same book')
        ,   (9, 'While we are postponing, life speeds by')
        ,   (9, 'Build your own dreams, or someone else will hire you to build theirs');